// apps/web/src/components/HeaderSection.tsx
'use client'

import Link from 'next/link'
import { useUserStore } from '@/store/userStore'

export default function HeaderSection() {
  const { isUserLoggedIn, logout } = useUserStore()

  return (
    <header className="bg-blue-600 text-white shadow-md">
      <div className="max-w-4xl mx-auto px-4 h-14 flex items-center gap-6">
        <Link href="/" className="font-bold text-lg mr-4 hover:opacity-90">
          TabTracker
        </Link>
        <Link href="/songs" className="hover:opacity-90">
          Browse
        </Link>
        <div className="flex-1" />
        {!isUserLoggedIn ? (
          <>
            <Link href="/login" className="hover:opacity-90">
              Login
            </Link>
            <Link href="/register" className="hover:opacity-90">
              Sign Up
            </Link>
          </>
        ) : (
          <Link href="/" onClick={logout} className="hover:opacity-90">
            Log Out
          </Link>
        )}
      </div>
    </header>
  )
}

// client/src/components/HeaderSection.vue
<template>
  <VAppBar color="blue" class="text-start">
    <VBtn height="100%" to="/">
      <VAppBarTitle class="mr-4"> TabTracker </VAppBarTitle>
    </VBtn>
    <VBtn flat height="100%" to="/songs">Browse</VBtn>
    <VSpacer></VSpacer>
    <VBtn v-if="!isUserLoggedIn" flat height="100%" to="/login"> Login </VBtn>
    <VBtn v-if="!isUserLoggedIn" flat height="100%" to="/register"> Sign Up </VBtn>
    <VBtn v-if="isUserLoggedIn" @click="logout" flat height="100%" to="/"> Log Out </VBtn>
  </VAppBar>
</template>

<script>
import { VAppBar, VAppBarTitle, VBtn, VSpacer } from 'vuetify/lib/components/index.mjs'
import { useUserStore } from '../stores/userStore'
import { storeToRefs } from 'pinia'

export default {
  data() {
    return {}
  },
  setup() {
    const userStore = useUserStore()
    const { isUserLoggedIn } = storeToRefs(userStore)
    return { userStore, isUserLoggedIn }
  },
  methods: {
    logout() {
      this.userStore.$reset()
    }
  },
  components: { VAppBar, VAppBarTitle, VBtn, VSpacer }
}
</script>

<style scoped>
.v-app-bar-title {
  flex: 0 0 auto;
}
</style>
